name: Release & Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write
  pages: write

jobs:
  build-release-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Bump version automatically (patch)
        id: bump
        run: |
          npm version patch -m "chore: bump version to %s"
          echo "version=$(node -p \"require('./package.json').version\")" >> $GITHUB_OUTPUT

      - name: Push bump commit + tag
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git push https://x-access-token:${{ secrets.ACTIONS_TOKEN }}@github.com/${{ github.repository }} HEAD:main --follow-tags

      - name: Build project
        run: |
          npm run build
          cp dist/index.html dist/404.html

      - name: Prepare clean-dist
        run: |
          rm -rf clean-dist
          mkdir clean-dist
          cp -rL dist/* clean-dist/
          find clean-dist -name "*.map" -delete
          find clean-dist -name "*.log" -delete

      - name: Create artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: clean-dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.bump.outputs.version }}
          name: Release v${{ steps.bump.outputs.version }}
          files: |
            clean-dist/**
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
